### PR TITLE
No env specific bundle for ESM

### LINKED ISSUE #140: Production bundle for ES format is not enough for a development
### Current Behavior

Webpack will use ES format but being in a development mode it means the wrong assumption from 3rd modules like `invariant` which then throws an error.

image

https://github.com/zertosh/invariant/blob/fae1c859f3eec25025dc6019bf7f7fdb78a27307/invariant.js#L26

### Expected behavior

Same behavior as for CJS should be used and provide development bundle along with `index.es.js`.

### Suggested solution(s)

Should be pretty straightforward to add a line in here...

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/index.ts#L98

And utilize logic for creating index file...

https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/index.ts#L277

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.6.1
| TypeScript       | 3.5.1
| Browser          | N/A
| Yarn         | 1.16.0
| Operating System | Windows x64

### PR DESCRIPTION
**Pull request by FredyC**
Fixes #140 

An alternative (and correct) approach based on a discussion in #141 

~~I've kept `index.js` which points to a single `name.cjs.js` file to keep breaking changes at a minimum. It could probably be removed eventually.~~

Besides some slight cleanup, the major change is a single ESM build that isn't env specific. Production bundles also get the `.min` in the name.

### CODE REVIEW

**Comment by FredyC** [comment]
Btw, I've noticed that for `watch` command it includes `umd` for format defaults while in `build` only `cjs,es` is by default. Looks like an oversight. Shall I fix it here as well?

File: src/index.ts [hunk 1]
```diff
@@ -267,23 +265,9 @@ prog
     opts.name = opts.name || appPackageJson.name;
     opts.input = await getInputs(opts.entry, appPackageJson.source);
     const buildConfigs = createBuildConfigs(opts);
+    await util.promisify(mkdirp)(resolveApp('dist'));
```
Comment (FredyC) [inline src/index.ts]: I haven't fully understood why this line was originally inside the condition. Why it shouldn't be creating dist folder no matter of what format is chosen?

**Comment by FredyC** [comment]
Perhaps I should also rename those umd bundles as drafted in https://github.com/palmerhq/tsdx/pull/141#issuecomment-501420287? It would be breaking change unless making alias files for that as well.

On the other hand, having `.min` (or not) does not tell the story that it's actually a production build. If something is minified is not that relevant and it's apparent from the first look at the file.

**Comment by TrySound** [comment]
I think UMD story similar to react is ok too.

**Comment by TrySound** [comment]
I would recommend to rename `es` into `esm`. Rollup supports both formats. `es` has different meaning in some projects. For example material-ui uses it for es6 syntax (not only for esm).

**Comment by FredyC** [comment]
@TrySound Well, in that case I would have to change the whole `--format esm` option which is another breaking change. Is that ok?

**Comment by TrySound** [comment]
Yeah, both umd and cjs are ok. The problem only esm bundle right now. @FredyC I think from tsdx point of view it can support both. `es` is an alias.

**Comment by FredyC** [comment]
Alright, another version. The CJS is back in both dev/prod builds. It also adds `min` to a production builds. The ES format now outputs like `dist/build-default.esm.js` without running replace. It's possible to input format as "es" or "esm", it gets normalized.

File: src/createRollupConfig.ts [hunk 2]
```diff
@@ -74,9 +88,7 @@ export function createRollupConfig(
     // Establish Rollup output
     output: {
       // Set filenames of the consumer's package
-      file: `${paths.appDist}/${safePackageName(
-        opts.name
-      )}.${format}.${env}.js`,
+      file: outputName,
       // Pass through the file format
       format,
```
Comment (TrySound) [inline src/createRollupConfig.ts]: You may add the same condition here to highlight migration to `esm`

Comment (FredyC) [reply src/createRollupConfig.ts]: Well, I am not sure to call it a migration. Or at least babel plugin typings expect the "es" only. Strangely enough, the rollup expects "esm" in the format option. I wonder how is it possible it actually worked till now. It's a bit of mess.

https://rollupjs.org/guide/en#command-line-flags

Comment (TrySound) [reply src/createRollupConfig.ts]: Babel do not use `es` value anywhere. The type is defined in this module.

Comment (FredyC) [reply src/createRollupConfig.ts]: Format is being passed to Babel in here ... https://github.com/palmerhq/tsdx/blob/943648edb06cd131f2c1751120cd1301804b480b/src/createRollupConfig.ts#L163

Either way, I've used the same condition for a rollup format.

Comment (TrySound) [reply src/createRollupConfig.ts]: I mean babelOptions is defined here too. Format is only used to check non-commonjs
https://github.com/palmerhq/tsdx/blob/d111c131a5e5cf19d62b98e123060c2ab55c43da/src/createRollupConfig.ts#L16-L50

Comment (FredyC) [reply src/createRollupConfig.ts]: Doh! How could I've missed that :) Ok, it's now consolidated as "esm" everywhere with a check for "es" to avoid breakage.

**Comment by FredyC** [comment]
So...anything else missing here? Would like to get it out soon-ish so we can publish a fixed package. I am kinda surprised that nobody else noticed it yet considering that Webpack grabs the ESM build by default.

**Comment by TrySound** [comment]
Latest release of formik uses old build. I guess that's why no one noticed.

File: src/index.ts [hunk 3]
```diff
@@ -383,6 +345,40 @@ prog
...
+function ensureDistFolder() {
+  return util.promisify(mkdirp)(resolveApp('dist'));
+}
+
+function writeCjsEntryFile(name: string) {
+  // prettier-ignore
+  const baseLine = `  module.exports = require('./${safePackageName(name)}`;
+  return fs.writeFile(
+    resolveApp(`./dist/index.js`),
+    [
```
[the remark this answers is not in the document]
Comment (FredyC) [reply src/index.ts]: I mostly wanted to fix the formatting, before it was like weird indentation all over the place. Do you really insist on such nitpick? :)

**Comment by jaredpalmer** [comment]
Yep

File: src/index.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (jaredpalmer) [reply src/index.ts]: Yep

[the remark this answers is not in the document]
Comment (jaredpalmer) [reply src/index.ts]: Yep

[the remark this answers is not in the document]
Comment (FredyC) [reply src/index.ts]: Ok, it's changed. Please try to get it out soon, it's fairly important fix.

**Comment by FredyC** [comment]
Can you release it this week, please?

**Comment by jaredpalmer** [comment]
Yup. On it meow.

**Comment by agilgur5** [comment]
@allcontributors please add @FredyC for code, docs, test, ideas

**Comment by agilgur5** [comment]
@allcontributors please add @TrySound for review, questions, ideas
