### PR TITLE
Better compilation via Babel

### LINKED ISSUE #109: Issue with node shebang
### Current Behavior

I could be doing something wrong here but creating a new "basic" project and adding the node shebang to `index.ts` and running `yarn build --target node` results in this error:

```sh
23:34:20 in tsdx-issue on  master is 📦  v0.1.0 via ⬢ v8.15.0 took 7s
➜ yarn build --target node
yarn run v1.15.2
warning package.json: No license field
$ tsdx build --target node
✓ Creating entry file 3.5 secs
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
(node:60781) UnhandledPromiseRejectionWarning: Error: Unexpected character '#' (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/malves/Development/tmp/tsdx-issue/node_modules/rollup/dist/rollup.js:9236:30)
    at Module.error (/Users/malves/Development/tmp/tsdx-issue/node_modules/rollup/dist/rollup.js:12909:9)
    at tryParse (/Users/malves/Development/tmp/tsdx-issue/node_modules/rollup/dist/rollup.js:12825:16)
    at Module.setSource (/Users/malves/Development/tmp/tsdx-issue/node_modules/rollup/dist/rollup.js:13102:33)
    at Promise.resolve.catch.then.then.then (/Users/malves/Development/tmp/tsdx-issue/node_modules/rollup/dist/rollup.js:15924:20)
    at <anonymous>
(node:60781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
✨  Done in 5.38s.
```

### Expected behavior

Should build without an error as far as I know. 

### Suggested solution(s)

Not quite sure where the issue lies here. Spent a bit of time digging around to see if maybe I could figure it out but wasn't very successful.

### Additional context

[Sample Repo](https://github.com/MarceloAlves/tsdx-issue)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.5.11
| TypeScript       | 3.4.5
| Browser          | Chrome 74
| npm/Yarn         | 1.15.2
| Operating System | macOS 10.14.4

### PR DESCRIPTION
**Pull request by jaredpalmer**
Use babel to do better compilation #102 . Fix #109 

We can/should discuss overrides and customization for both babel and rollup and stuff in another issue.

### CODE REVIEW

File: src/createRollupConfig.ts [hunk 1]
```diff
@@ -117,15 +169,12 @@ export function createRollupConfig(
           compress: {
             keep_infinity: true,
             pure_getters: true,
-            collapse_vars: false,
+            passes: 10,
```
Comment (sw-yx) [inline src/createRollupConfig.ts]: does this do the same job as `collapse_vars`? i added that because it is buggy otherwise
